export const RouteApi = {
    login: '/auth/login',
    profile: '/auth/profile',
    data_master: '/works/master',
    addDataMaster: '/works/addNewData',
    addWork: '/works/create',
    getWorks: '/works/getData',
    deleteWork: '/works/delete',
    detailWork: '/works/getDetailWork',
    updateWork: '/works/update',
    uploadImageEditor: '/works/uploadImageEditor',
    getColors: 'color/colors',
    addModel: 'model/add',
    getModels: 'model/getAll',
};